# Wayland & Ozone Architecture
--ozone-platform-hint=auto
--ozone-platform=wayland
--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebGPUService,VaapiVideoDecoder,VaapiVideoEncoder,HeliumMiddleClickAutoscroll

# Color Management & HDR
--enable-hdr
--force-color-profile=scrgb-linear

# Hardware Acceleration & GPU Overrides
--ignore-gpu-blocklist
--enable-zero-copy

--disable-features=HardwareMediaKeyHandling
